In [111]:
import numpy as np

#Question 1


1. Initialize an all one array with size 4x2


In [81]:
array = np.empty((2,2))
print(array)

[[3.84402111e-315 0.00000000e+000]
 [3.84733385e-315 6.83100630e-310]]


Initialize an all one array with size 4x2.

In [82]:
array_1=np.ones((4,2))
print(array_1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.

In [83]:
array_2 = np.full((3,3),7)
print(array_2)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of 0's with same shape and type as a given array.

In [84]:
a1 = np.array([[1,2,3]])
array_3 = np.zeros_like(a1)
print(array_3)

[[0 0 0]]


5. Return a new array of ones with same shape and type as a given array.

In [85]:
a2 = np.array([[5,6,7]])
array_4 = np.ones_like(a2)
print(array_4)

[[1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to numpy


In [86]:
new_list = [1,2,3,4]
array_5 = np.array(new_list)
print(array_5)

[1 2 3 4]


Problem 2: Array Manipulation

1. Create an array with values ranging from 10 to 49.

In [87]:
array_6 = np.arange(10,50)
print(array_6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3x3 matrix with values ranging from 0 to 8.

In [88]:
array_7 = np.arange(0,9).reshape(3,3)
print(array_7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3x3 identitiy matrix.

In [89]:
array_9 = np.eye(3)
print(array_9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

In [90]:
array_10 = np.random.random(30)
mean = np.mean(array_10)
print("Mean = ",mean)

Mean =  0.5717598269866024


5.Create a 10X10 array with random values and find the minimum and maximum values.

In [91]:
array_11 = np.random.random((10,10))
min_arr = array_11.min()
max_arr = array_11.max()
print("Minimum = ",min_arr)
print("Maximum = ",max_arr)

Minimum =  0.023573405760525912
Maximum =  0.9823205704031256


6. Create a zero array of size 10 and replace 5th element with 1.

In [92]:
array_12 = np.zeros(10)
array_12[4] = 1
print(array_12)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0]

In [93]:
arr = np.array([1,2,0,0,4,0])
rev_arr = arr[::-1]
print("Reversed array : ", rev_arr)

Reversed array :  [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and o inside

In [94]:
array_13 = np.ones((5,5))
array_13[1:-1,1:-1] = 0
print("Bordered array: \n",array_13)

Bordered array: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [95]:
n = np.zeros((8,8))
n[1::2,::2] = 1
n[::2, 1::2] = 1
print("Checkerboard pattern: \n",n)


Checkerboard pattern: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3


In [96]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


1. Add the two array

In [97]:
add1 = x + y
add2 = v + w
print("Addition of x and y: ", add1)
print("Addition of v and w : ",add2)

Addition of x and y:  [[ 6  8]
 [10 13]]
Addition of v and w :  [20 22]


2. Subtract the two array

In [98]:
sub1 = x -y
sub2 = v - w
print("Subtraction of x and y: ", sub1)
print("Subtraction of v and w : ",sub2)

Subtraction of x and y:  [[-4 -4]
 [-4 -3]]
Subtraction of v and w :  [-2 -2]


3. Multiply the array with any integers of your choice

In [99]:
mul1 = x*2
mul2 = y*2
mul3 = v*2
mul4 = w*2
print("Multiplication of x with 2 = ", mul1)
print("Multiplication of y with 2 = ", mul2)
print("Multiplication of v with 2 = ", mul3)
print("Multiplication of w with 2 = ", mul4)

Multiplication of x with 2 =  [[ 2  4]
 [ 6 10]]
Multiplication of y with 2 =  [[10 12]
 [14 16]]
Multiplication of v with 2 =  [18 20]
Multiplication of w with 2 =  [22 24]


4. Find the square of each element of the array.

In [100]:
square_x = x**2
square_y = y**2
square_v = v**2
square_w = w**2
print("Square of x ", square_x)
print("Square of y ", square_y)
print("Square of v ", square_v)
print("Square of w ", square_w)

Square of x  [[ 1  4]
 [ 9 25]]
Square of y  [[25 36]
 [49 64]]
Square of v  [ 81 100]
Square of w  [121 144]


5. Find the dot product between:  v(and)w ; x(and)v ; x(and)y.

In [101]:
dot_1 = np.dot (v,w)
dot_2 = np.dot (x,v)
dot_3 = np.dot (x,y)
print("Dot product of v and w = ", dot_1)
print("Dot product of x and v = ", dot_2)
print("Dot product of x and y = ", dot_3)

Dot product of v and w =  219
Dot product of x and v =  [29 77]
Dot product of x and y =  [[19 22]
 [50 58]]


6.Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [102]:
conc_row = np.concatenate((x,y), axis=0)
conc_col = np.vstack((v,w))
print("Concatenation along row: \n",conc_row)
print("Concatenation along column: \n",conc_col)

Concatenation along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation along column: 
 [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [103]:
conc_xv = np.concatenate((x,v))
print(conc_xv)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem 4: Matrix Operations:


In [104]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1. Prove A.A-1 = I

In [105]:
A_inverse = np.linalg.inv(A)
identity = np.dot(A,A_inverse)
print("A.A-inverse = I : \n", identity)

A.A-inverse = I : 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB/=BA

In [106]:
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB: \n", AB)
print("BA: \n", BA)
print("Is AB = BA : ",np.array_equal(AB,BA))

AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Is AB = BA :  False


Prove (AB)T = BTAT

In [107]:
AB_transpose = AB.T
B_transpose = B.T
A_transpose = A.T
AT_BT = np.dot(A.T,B.T)
print("AB transpose: \n", AB_transpose)
print("A transpose B transpose: \n", AT_BT)
print("Is ABT = AT.BT : ",np.array_equal(AB_transpose,AT_BT))

AB transpose: 
 [[23 51]
 [13 29]]
A transpose B transpose: 
 [[36 13]
 [44 16]]
Is ABT = AT.BT :  False


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [108]:
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])

In [109]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
print("X[x,y,z]= ",X)

X[x,y,z]=  [ 2.  1. -2.]


In [110]:
X1 = np.linalg.solve(A,B)
print("X[x,y,z]= ",X1)

X[x,y,z]=  [ 2.  1. -2.]
